logging:
  level:
    org:
      hibernate:
        type: trace
    study:
      hibernate: debug
server:
  port: 8090
spring:
  config:
    activate: 
      on-profile: local  
  datasource:
    url: jdbc:h2:~/hibernate
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
  devtools.livereload.enabled: true

---
logging:
  level:
    org:
      hibernate:
        type: trace
    study:
      hibernate: debug
server:
  port: 8090
spring:
  config:
    activate: 
      on-profile: test  
  datasource:
    url: jdbc:h2:~/hibernate
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
  devtools.livereload.enabled: true
